kind: pipeline
type: docker
name: container-structure-test

steps:
  - name: build
    image: plugins/docker
    volumes:
      - name: docker-sock
        path: /var/run/docker.sock
    settings:
      repo: plugins/container-structure-test
      tags: latest
      context: container-structure-test
      dockerfile: container-structure-test/Dockerfile
      dry_run: true

volumes:
  - name: docker-sock
    host:
      path: /var/run/docker.sock

---
kind: pipeline
type: docker
name: namcap

steps:
  - name: build
    image: plugins/docker
    volumes:
      - name: docker-sock
        path: /var/run/docker.sock
    settings:
      repo: plugins/namcap
      tags: latest
      context: namcap
      dockerfile: namcap/Dockerfile
      dry_run: true

volumes:
  - name: docker-sock
    host:
      path: /var/run/docker.sock
